// Generated by https://quicktype.io

export interface InfoPagina {
    titulo?:       string;
    email?:        string;
    nombre_corto?: string;
    facebook?:     string;
    twitter?:      string;
    instagram?:    string;
    github?:       string;
    linkedin?:     string;
    phone?:        string;
    familia?:      any[];
}
